db:
  name: wp-database
  labels:
    id: c0929851
    app: db
    env: dev
    stack: wordpress
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: "c0929851"
    MYSQL_USER: "3324_user"
    APP_ENV: dev
  containerPorts:
      mysql: 3306

