nginx:
  name: c0929851
  labels:
    id: c0929851
    app: nginx
    env: dev
    stack: wordpress
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: c0929851
    MYSQL_USER: 3324_user
    APP_ENV: dev
  containerPorts:
      mysql: 3306
  service:
    type: LoadBalancer
    port: 80

  replicaCount: 1
